api_dict = {
    "player":
        "https://api.stratz.com/api/v1/Player/{}{}",
    "player_matches":
        "https://api.stratz.com/api/v1/Player/{}/matches{}",
    "player_matches_opendota":
        "https://api.opendota.com/api/players/{}/recentMatches",
    "player_hero":
        "https://api.stratz.com/api/v1/Player/{}/heroPerformance/{}?gameMode=1,2,3,4",
    "match":
        "https://api.opendota.com/api/matches/{}",
    "match_story":
        'https://www.opendota.com/matches/{}/story',
    "match_request":
        'https://www.opendota.com/request#{}',
}

hero_dict = {
    "1": "敌法师",
    "2": "斧王",
    "3": "祸乱之源",
    "4": "血魔",
    "5": "水晶室女",
    "6": "卓尔游侠",
    "7": "撼地者",
    "8": "主宰",
    "9": "米拉娜",
    "10": "变体精灵",
    "11": "影魔",
    "12": "幻影长矛手",
    "13": "帕克",
    "14": "帕吉",
    "15": "剃刀",
    "16": "沙王",
    "17": "风暴之灵",
    "18": "斯温",
    "19": "小小",
    "20": " 复仇之魂",
    "21": "风行者",
    "22": "宙斯",
    "23": "昆卡",
    "25": "莉娜",
    "26": "莱恩",
    "27": "暗影萨满",
    "28": "斯拉达",
    "29": "潮汐猎人",
    "30": "巫医",
    "31": "巫妖",
    "32": "力丸",
    "33": "谜团",
    "34": "修补匠",
    "35": "狙击手",
    "36": "瘟疫法师",
    "37": "术士",
    "38": "兽王",
    "39": "痛苦女王",
    "40": "剧毒术士",
    "41": "虚空假面",
    "42": "冥魂大帝",
    "43": "死亡先知",
    "44": "幻影刺客",
    "45": "帕格纳",
    "46": "圣堂刺客",
    "47": "冥界亚龙",
    "48": "露娜",
    "49": "龙骑士",
    "50": "戴泽",
    "51": "发条技师",
    "52": "拉席克",
    "53": "先知",
    "54": "噬魂鬼",
    "55": "黑暗贤者",
    "56": "克林克兹",
    "57": "全能骑士",
    "58": "魅惑魔女",
    "59": "哈斯卡",
    "60": "暗夜魔王",
    "61": "育母蜘蛛",
    "62": "赏金猎人",
    "63": "编织者",
    "64": "杰奇洛",
    "65": "蝙蝠骑士",
    "66": "陈",
    "67": "幽鬼",
    "68": "远古冰魄",
    "69": "末日使者",
    "70": "熊战士",
    "71": "裂魂人",
    "72": "矮人直升机",
    "73": "炼金术士",
    "74": "祈求者",
    "75": "沉默术士",
    "76": "殁境神蚀者",
    "77": "狼人",
    "78": "酒仙",
    "79": "暗影恶魔",
    "80": "德鲁伊",
    "81": "混沌骑士",
    "82": "米波",
    "83": "树精卫士",
    "84": "食人魔魔法师",
    "85": "不朽尸王",
    "86": "拉比克",
    "87": "干扰者",
    "88": "司夜刺客",
    "89": "娜迦海妖",
    "90": "光之守卫",
    "91": "艾欧",
    "92": "维萨吉",
    "93": "斯拉克",
    "94": "美杜莎",
    "95": "巨魔战将",
    "96": "半人马战行者",
    "97": "马格纳斯",
    "98": "伐木机",
    "99": "钢背兽",
    "100": "巨牙海民",
    "101": "天怒法师",
    "102": "亚巴顿",
    "103": "上古巨神",
    "104": "军团指挥官",
    "105": "工程师",
    "106": "灰烬之灵",
    "107": "大地之灵",
    "108": "孽主",
    "109": "恐怖利刃",
    "110": "凤凰",
    "111": "神谕者",
    "112": "寒冬飞龙",
    "113": "天穹守望者",
    "114": "齐天大圣",
    "119": "邪影芳灵",
    "120": "石鳞剑士",
    "121": "天涯墨客",
    "126": "虚无之灵",
    "128": "电炎绝手",
    "129": "玛尔斯",
}
hero_dict_en = {
    "1": "Anti-Mage",
    "2": "Axe",
    "3": "Bane",
    "4": "Bloodseeker",
    "5": "Crystal Maiden",
    "6": "Drow Ranger",
    "7": "Earthshaker",
    "8": "Juggernaut",
    "9": "Mirana",
    "10": "Morphling",
    "11": "Shadow Fiend",
    "12": "Phantom Lancer",
    "13": "Puck",
    "14": "Pudge",
    "15": "Razor",
    "16": "Sand King",
    "17": "Storm Spirit",
    "18": "Sven",
    "19": "Tiny",
    "20": "Vengeful Spirit",
    "21": "Windranger",
    "22": "Zeus",
    "23": "Kunkka",
    "25": "Lina",
    "26": "Lion",
    "27": "Shadow Shaman",
    "28": "Slardar",
    "29": "Tidehunter",
    "30": "Witch Doctor",
    "31": "Lich",
    "32": "Riki",
    "33": "Enigma",
    "34": "Tinker",
    "35": "Sniper",
    "36": "Necrophos",
    "37": "Warlock",
    "38": "Beastmaster",
    "39": "Queen of Pain",
    "40": "Venomancer",
    "41": "Faceless Void",
    "42": "Wraith King",
    "43": "Death Prophet",
    "44": "Phantom Assassin",
    "45": "Pugna",
    "46": "Templar Assassin",
    "47": "Viper",
    "48": "Luna",
    "49": "Dragon Knight",
    "50": "Dazzle",
    "51": "Clockwerk",
    "52": "Leshrac",
    "53": "Nature's Prophet",
    "54": "Lifestealer",
    "55": "Dark Seer",
    "56": "Clinkz",
    "57": "Omniknight",
    "58": "Enchantress",
    "59": "Huskar",
    "60": "Night Stalker",
    "61": "Broodmother",
    "62": "Bounty Hunter",
    "63": "Weaver",
    "64": "Jakiro",
    "65": "Batrider",
    "66": "Chen",
    "67": "Spectre",
    "68": "Ancient Apparition",
    "69": "Doom",
    "70": "Ursa",
    "71": "Spirit Breaker",
    "72": "Gyrocopter",
    "73": "Alchemist",
    "74": "Invoker",
    "75": "Silencer",
    "76": "Outworld Devourer",
    "77": "Lycan",
    "78": "Brewmaster",
    "79": "Shadow Demon",
    "80": "Lone Druid",
    "81": "Chaos Knight",
    "82": "Meepo",
    "83": "Treant Protector",
    "84": "Ogre Magi",
    "85": "Undying",
    "86": "Rubick",
    "87": "Disruptor",
    "88": "Nyx Assassin",
    "89": "Naga Siren",
    "90": "Keeper of the Light",
    "91": "Io",
    "92": "Visage",
    "93": "Slark",
    "94": "Medusa",
    "95": "Troll Warlord",
    "96": "Centaur Warrunner",
    "97": "Magnus",
    "98": "Timbersaw",
    "99": "Bristleback",
    "100": "Tusk",
    "101": "Skywrath Mage",
    "102": "Abaddon",
    "103": "Elder Titan",
    "104": "Legion Commander",
    "105": "Techies",
    "106": "Ember Spirit",
    "107": "Earth Spirit",
    "108": "Underlord",
    "109": "Terrorblade",
    "110": "Phoenix",
    "111": "Oracle",
    "112": "Winter Wyvern",
    "113": "Arc Warden",
    "114": "Monkey King",
    "119": "Dark Willow",
    "120": "Pangolier",
    "121": "Grimstroke",
    "126": "Void Spirit",
    "128": "Snapfire",
    "129": "Mars",
}
